/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiRssRouteImport } from './routes/api/rss'
import { Route as ApiCheckAuthRouteImport } from './routes/api/check-auth'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAuthenticateRouteImport } from './routes/api/authenticate'
import { Route as ApiOgProxyRouteImport } from './routes/api/og/proxy'
import { Route as ApiOgGenerateRouteImport } from './routes/api/og/generate'
import { Route as ApiOgFetchRouteImport } from './routes/api/og/fetch'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiRssRoute = ApiRssRouteImport.update({
  id: '/api/rss',
  path: '/api/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckAuthRoute = ApiCheckAuthRouteImport.update({
  id: '/api/check-auth',
  path: '/api/check-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthenticateRoute = ApiAuthenticateRouteImport.update({
  id: '/api/authenticate',
  path: '/api/authenticate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgProxyRoute = ApiOgProxyRouteImport.update({
  id: '/api/og/proxy',
  path: '/api/og/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgGenerateRoute = ApiOgGenerateRouteImport.update({
  id: '/api/og/generate',
  path: '/api/og/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgFetchRoute = ApiOgFetchRouteImport.update({
  id: '/api/og/fetch',
  path: '/api/og/fetch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRouteWithChildren
  '/api/authenticate': typeof ApiAuthenticateRoute
  '/api/chat': typeof ApiChatRoute
  '/api/check-auth': typeof ApiCheckAuthRoute
  '/api/rss': typeof ApiRssRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/og/fetch': typeof ApiOgFetchRoute
  '/api/og/generate': typeof ApiOgGenerateRoute
  '/api/og/proxy': typeof ApiOgProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/authenticate': typeof ApiAuthenticateRoute
  '/api/chat': typeof ApiChatRoute
  '/api/check-auth': typeof ApiCheckAuthRoute
  '/api/rss': typeof ApiRssRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/blog': typeof BlogIndexRoute
  '/work': typeof WorkIndexRoute
  '/api/og/fetch': typeof ApiOgFetchRoute
  '/api/og/generate': typeof ApiOgGenerateRoute
  '/api/og/proxy': typeof ApiOgProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRouteWithChildren
  '/api/authenticate': typeof ApiAuthenticateRoute
  '/api/chat': typeof ApiChatRoute
  '/api/check-auth': typeof ApiCheckAuthRoute
  '/api/rss': typeof ApiRssRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/og/fetch': typeof ApiOgFetchRoute
  '/api/og/generate': typeof ApiOgGenerateRoute
  '/api/og/proxy': typeof ApiOgProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/gallery'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/work'
    | '/api/authenticate'
    | '/api/chat'
    | '/api/check-auth'
    | '/api/rss'
    | '/blog/$slug'
    | '/work/$slug'
    | '/blog/'
    | '/work/'
    | '/api/og/fetch'
    | '/api/og/generate'
    | '/api/og/proxy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gallery'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/authenticate'
    | '/api/chat'
    | '/api/check-auth'
    | '/api/rss'
    | '/blog/$slug'
    | '/work/$slug'
    | '/blog'
    | '/work'
    | '/api/og/fetch'
    | '/api/og/generate'
    | '/api/og/proxy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/gallery'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/work'
    | '/api/authenticate'
    | '/api/chat'
    | '/api/check-auth'
    | '/api/rss'
    | '/blog/$slug'
    | '/work/$slug'
    | '/blog/'
    | '/work/'
    | '/api/og/fetch'
    | '/api/og/generate'
    | '/api/og/proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkRoute: typeof WorkRouteWithChildren
  ApiAuthenticateRoute: typeof ApiAuthenticateRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCheckAuthRoute: typeof ApiCheckAuthRoute
  ApiRssRoute: typeof ApiRssRoute
  ApiOgFetchRoute: typeof ApiOgFetchRoute
  ApiOgGenerateRoute: typeof ApiOgGenerateRoute
  ApiOgProxyRoute: typeof ApiOgProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof WorkRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/rss': {
      id: '/api/rss'
      path: '/api/rss'
      fullPath: '/api/rss'
      preLoaderRoute: typeof ApiRssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-auth': {
      id: '/api/check-auth'
      path: '/api/check-auth'
      fullPath: '/api/check-auth'
      preLoaderRoute: typeof ApiCheckAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/authenticate': {
      id: '/api/authenticate'
      path: '/api/authenticate'
      fullPath: '/api/authenticate'
      preLoaderRoute: typeof ApiAuthenticateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/proxy': {
      id: '/api/og/proxy'
      path: '/api/og/proxy'
      fullPath: '/api/og/proxy'
      preLoaderRoute: typeof ApiOgProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/generate': {
      id: '/api/og/generate'
      path: '/api/og/generate'
      fullPath: '/api/og/generate'
      preLoaderRoute: typeof ApiOgGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/fetch': {
      id: '/api/og/fetch'
      path: '/api/og/fetch'
      fullPath: '/api/og/fetch'
      preLoaderRoute: typeof ApiOgFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface WorkRouteChildren {
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  GalleryRoute: GalleryRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkRoute: WorkRouteWithChildren,
  ApiAuthenticateRoute: ApiAuthenticateRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCheckAuthRoute: ApiCheckAuthRoute,
  ApiRssRoute: ApiRssRoute,
  ApiOgFetchRoute: ApiOgFetchRoute,
  ApiOgGenerateRoute: ApiOgGenerateRoute,
  ApiOgProxyRoute: ApiOgProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
